// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachersAndPupils;

#nullable disable

namespace TeachersAndPupils.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926143604_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachersAndPupils.Models.Pupil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "30-A",
                            FirstName = "დავით",
                            Gender = "M",
                            LastName = "დავითაშვილი"
                        },
                        new
                        {
                            Id = 2,
                            Class = "30-B",
                            FirstName = "ელენე",
                            Gender = "F",
                            LastName = "ელენიძე"
                        },
                        new
                        {
                            Id = 3,
                            Class = "30-A",
                            FirstName = "ანა",
                            Gender = "F",
                            LastName = "ანანიაშვილი"
                        },
                        new
                        {
                            Id = 4,
                            Class = "30-B",
                            FirstName = "გიორგი",
                            Gender = "M",
                            LastName = "ჩხარტიშვილი"
                        });
                });

            modelBuilder.Entity("TeachersAndPupils.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "გიორგი",
                            Gender = "M",
                            LastName = "გიორგაძე",
                            Subject = "ბიოლოგია"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "ზურაბ",
                            Gender = "M",
                            LastName = "ზურაბიანი",
                            Subject = "მათემატიკა"
                        });
                });

            modelBuilder.Entity("TeachersAndPupils.Models.TeacherPupil", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("PupilId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "PupilId");

                    b.HasIndex("PupilId");

                    b.ToTable("TeacherPupils");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            PupilId = 1
                        },
                        new
                        {
                            TeacherId = 1,
                            PupilId = 2
                        },
                        new
                        {
                            TeacherId = 2,
                            PupilId = 3
                        },
                        new
                        {
                            TeacherId = 1,
                            PupilId = 4
                        });
                });

            modelBuilder.Entity("TeachersAndPupils.Models.TeacherPupil", b =>
                {
                    b.HasOne("TeachersAndPupils.Models.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachersAndPupils.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pupil");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
